
PIQIC = $(REBAR_DEPS_DIR)/piqi/priv/bin/piqic-erlang-ext
PIQIC_FLAGS =


PIQI_FILES = erlmpc.piqi

PIQI_ERL_FILES = erlmpc_piqi.erl erlmpc_piqi_ext.erl
PIQI_HRL_FILES = erlmpc_piqi.hrl

PIQI_ERLANG_FILES = $(PIQI_ERL_FILES) $(PIQI_HRL_FILES)


all: $(PIQI_ERLANG_FILES)


$(PIQI_ERLANG_FILES): $(PIQI_FILES)
	set -e; \
	for i in $^; do \
		$(PIQIC) $(PIQIC_FLAGS) $$i; \
	done


clean:
	rm -f $(PIQI_ERLANG_FILES)

